const mongoose = require("mongoose");

const userSchema = new mongoose.Schema(
  {
    userId: { type: String, required: true, unique: true },
    fullName: { type: String, required: true },
    email: { type: String, required: true, unique: true, lowercase: true },
    mobile: { type: String, required: true },
    role: {
      type: String,
      enum: ["Admin", "Recruiter"],
      required: true,
    },
    department: { type: String },
    status: {
      type: String,
      enum: ["Active", "Inactive"],
      default: "Active",
    },
    passwordHash: { type: String, required: true },
    autoGeneratedPassword: { type: Boolean, default: false },
    lastLogin: { type: Date },
  },
  {
    timestamps: { createdAt: true, updatedAt: "updatedAt" },
  }
);

module.exports = mongoose.model("User", userSchema);
